//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crm.Services
{
    using Crm.Model;
    using Crm.IServices;
     using Crm.IRepository;
    
    public partial class wfWorkNodesServices:BaseServices<wfWorkNodes>,IwfWorkNodesServices
    {
       /// <summary>
      /// 注意在构造函数中要对父类中的dal 进行一次赋值
     /// </summary>
      IwfWorkNodesDal subdal;
       public wfWorkNodesServices(IwfWorkNodesDal subdal)
       {
    		base.dal = subdal;
            this.subdal = subdal;
       }
      
    
      
      
      
      
      
      
      
      
      
      
      
      
      
      
    
     
     
     
     
     
     
    }
}
